
/* This file was auto-generated by script file.
 * For iSCSI pre-posting, some functions declared by other layer didn't be
 * implemented yet, so we use weak symbol mechanism to avoid the compliler
 * will complain during to compile / link them. But, for some functions which
 * were declared by 'static' or 'inline', we shall use another way to solve this
 */
#ifndef ISCSI_AUTOGEN_H
#define ISCSI_AUTOGEN_H
	

#define __HAVE_RQ_GET_THIN_HOOK__
	
#endif

